spring.application.name=api-gateway
server.port=1000

# Discovery Client
eureka.instance.instance-id=${spring.application.name}:${random.uuid}
eureka.client.service-url.defaultZone=http://localhost:8090/eureka/

# Routes
spring.cloud.gateway.server.webflux.routes[0].id=user-microservice
spring.cloud.gateway.server.webflux.routes[0].uri=lb://USER-MICROSERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/user/**

# Spring Security
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-8yt6f555y2l6kaad.us.auth0.com/