spring.application.name=product-microservice
server.port=8091

# Conexión a PostgreSQL usando R2DBC
spring.r2dbc.url=r2dbc:postgresql://host.docker.internal:5432/db_shop_products
spring.r2dbc.username=postgres
spring.r2dbc.password=95700909

# Pool de conexiones (Reactivo)
spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=5
spring.r2dbc.pool.max-size=20

# Mostrar logs SQL (info - menos verboso)
logging.level.org.springframework.r2dbc=INFO

# Health Check
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true

# Discovery Client
# :${random.uuid}
eureka.instance.instance-id=${spring.application.name}
eureka.client.serviceUrl.defaultZone=http://host.docker.internal:8090/eureka

# Circuit Breaker con Resilience4j
resilience4j.circuitbreaker.instances.getAllProductsCircuitBreaker.base-config=default
resilience4j.circuitbreaker.instances.getAllProductsCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.getProductByIdCircuitBreaker.base-config=default
resilience4j.circuitbreaker.instances.getProductByIdCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.insertProductCircuitBreaker.base-config=default
resilience4j.circuitbreaker.instances.insertProductCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.updateProductByIdCircuitBreaker.base-config=default
resilience4j.circuitbreaker.instances.updateProductByIdCircuitBreaker.failureRateThreshold=50

resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=5
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.configs.default.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=5s
resilience4j.circuitbreaker.configs.default.slowCallRateThreshold=50
resilience4j.circuitbreaker.configs.default.event-consumer-buffer-size=10

logging.level.io.github.resilience4j=WARN
logging.level.org.springframework.aop=WARN

logging.level.org.springframework.web=ERROR
logging.level.reactor.netty=ERROR

# Kafka Producer config
# pring.kafka.bootstrap-servers=kafka:9092
spring.kafka.bootstrap-servers=172.17.0.2:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
